RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    g++ \
    gcc \
    libc6-dev \
    make \
    python3 \
    libglib2.0-0 \
    libnss3 \
    libx11-6 \
    libx11-xcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxi6 \
    libxtst6 \
    libxrandr2 \
    libasound2 \
    libpango-1.0-0 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libgtk-3-0 \
    libgbm-dev

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
